apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfchainbridgeui.fullname" . }}
  labels:
    {{- include "tfchainbridgeui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "tfchainbridgeui.selectorLabels" . | nindent 4 }}
