# Default values for tfchainbridgeui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tfchainbridgeui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

global:
  ingress:
    certresolver: le

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host:
      paths: 
        - /
  tls: []

#url: wss://tfchain.dev.threefold.io
#url: wss://tfchain.test.threefold.io
url: 

# dev url (devnet tfts)
#stellar_horizon_url: https://horizon-testnet.stellar.org

# main url (mainnet & test tft)
#stellar_horizon_url: https://horizon.stellar.org

stellar_horizon_url:

# tft on testnet issuer (can be used for dev only)
#tft_asset_issuer: GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3

# tft on mainnet issuer (can be used for testnet and mainnet)
#tft_asset_issuer: GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47

tft_asset_issuer:

# devnet bridge address (can be used for dev only)
#stellar_bridge_address: GCMBZY4NGEV4CQYHJ6SXMRSTLTEOR2ERNKY6NH32LYCVDCN2E5CXZJOU

# testnet bridge address (can be used for testnet and mainnet)
#stellar_bridge_address: GA2CWNBUHX7NZ3B5GR4I23FMU7VY5RPA77IUJTIXTTTGKYSKDSV6LUA4

stellar_bridge_address:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 900m
  #   memory: 1000Mi

nodeSelector: {}

tolerations: []

affinity: {}

threefoldVdc:
  backup: ''